import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../styles/globals.scss";
// import { LayoutSite } from "@/components/layout/LayoutSite";

const montserrat = Montserrat({
  variable: "--font-Montserrat-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}>
        {children}
      </body>
    </html>
  );
}
